### ISSUE TITLE
Does not work with Windows (32-bit)

### ISSUE THREAD

**Issue by ponmudivn** [sindresorhus/clipboardy#30]
Cannot use the module in windows 32 bit device. 
```

let clipboardy = require('clipboardy');

//With clipboardy
for (let index = 0; index < 5; index++) {
    let value = 'test' + index;
    clipboardy.writeSync(value);
    console.log(clipboardy.readSync());
} 
```

Running above code throws following error

```
$ node clipboardy_test.js
<...\node_modules\execa\index.js:277>
                throw (result.error || new Error(result.stderr === '' ? result.stdout : result.stderr));
                ^

Error: spawnSync <...\node_modules\clipboardy\fallbacks\windows\copy.exe> UNKNOWN
    at exports._errnoException (util.js:1026:11)
    at Object.spawnSync (child_process.js:461:20)
    at Function.module.exports.sync (<...\node_modules\execa\index.js:274:30>)
    at Object.copySync (<...\node_modules\clipboardy\lib\windows.js:12:26>)
    at Object.exports.writeSync.input [as writeSync] (<...\node_modules\clipboardy\index.js:38:13>)
    at Object.<anonymous> (<...\clipboardy_test.js:6:16>)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

Then on checking the ' clipboardy \ fallbacks \ windows \ copy.exe' it seems that it supports only 64 bit.

` clipboardy \ fallbacks \ windows \ copy.exe is not compatible with running Windows version. Check the system information of the computer and check whether the version of x86 (32 bit) or x64 (64 bit) of the program is required before contacting the software publisher. `

This is expected or am i missing something.

My environment: 
Node : v6.5.0
Clipboardy: v1.1.4
OS: windows 7 - 32bit

Thanks

**Comment by floatdrop** [comment]
@ponmudivn yeah, we built binaries only for x64 platform – https://github.com/sindresorhus/win-clipboard/blob/master/appveyor.yml#L3

**Comment by Mnrikard** [comment]
I've forked this with the copy/paste exe's for windows written in .NET for AnyCPU.  It works for me, but what's the consensus on a managed/intermediate language app instead of a natively compiled app?  I haven't issued a PR yet because I don't know if this is what you want.  It also fixes the \r\r\n problem from #27

**Comment by floatdrop** [comment]
@Mnrikard one of the goals of natively compiled binaries is to be as fast as possible, because there are a lot of use cases for copy-pasting large amount of data (around megabytes) in code editors. It should work fast. Some time ago we just used power-shell script, that worked on any windows, but suffer from poor performance.

Can you tell, how you fix `\r\r\n` or make a PR in to [win-clipboard](https://github.com/sindresorhus/win-clipboard)?

**Comment by Mnrikard** [comment]
fixing the \r\r\n issue was fixed just by using .NET's System.Windows.Clipboard  I just wrote the string to it.  I took a look at the win-clipboard, it's not obvious where the problem is coming from in there.  I'll try to take a look later.  Also, yes, after having the .NET copy/paste for about a week, I got tired of the slowness and moved back to the natively compiled ones.

**Comment by ianpgall** [comment]
FYI - I don't think the PR detects the OS arch correctly. It uses `process.arch` (acts the same as `os.arch()`), which unfortunately detects the current process's arch. That means if you have a 64-bit OS, and 32-bit Node.js installed, it will report as 32-bit. The 32-bit EXE still works for me on the 64-bit OS, I just didn't know how important it was for a 64-bit OS to use the 64-bit EXE (it's probably ideal, but not required).
And trust me, I wouldn't be in this scenario (64-bit OS with 32-bit Node.js) except it's required for the project I'm working on.
An option I found to get the true OS arch is to use: https://github.com/feross/arch

**Comment by floatdrop** [comment]
@ianpgall True. Can you make a PR with fix?

**Comment by ianpgall** [comment]
@floatdrop Sure thing! I just wanted to post here first to make sure what I was claiming wasn't crazy
